### ISSUE TITLE
[Bug]: wisp level effects dont sync to other players?

### ISSUE THREAD

**Issue by snorasaur** [Digitalroot-Valheim/Digitalroot.Valheim.BetterWisps#2]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

my wisp is level 1, my friends is level 4.  if he puts his wisp away, but mine is still out, i will have level 1 effects, but he can still see further away, as if my wisp was level 4.

so i cant benefit from his higher level wisp, but my wisp acts like it is level 4 on his game, but acts like its level 1 on mine, at the same time.

### To Reproduce

make a dedi server
install this mod, and its 2 pre reqs on the dedi and your client. have a friend do the same on his client
have him join your game
one of u level up your wisp, one of u dont
have the low wisp client have his wisp out, have the high wisp client put his wisp away
go to mistlands, have the low level wisp client mark his max visual distance, have the high level client stand in the same spot, and he will be able to see much further than the low level client, despite him not having the high level wisp equipped.

not a big deal, but i thought u may wanna know.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
That is fascinating. What a great bug to find. I'll have to take a look at it and see if there's anything I can do about it. Thanks for the report.

**Comment by Digitalroot** [comment]
Not going to fix this.
