### ISSUE TITLE
[Bug]: Better Wisp mod not compatible with JewelCrafting from Blaxxun

### ISSUE THREAD

**Issue by Atylon63** [Digitalroot-Valheim/Digitalroot.Valheim.BetterWisps#3]
### How are you playing the game?

Single Player - No Server

### What happened?

Hey, I'm using JewelCrafting (very well known mod made by Smoothbrain aka blaxxun on the Odin Plus Discord) since it make accessories usable as "gems" and able to put them in item slots.
The Wisp works on lvl 1 with no problem, able to put it in any accessory slot etc. But as soon as I upgrade it to lvl 2 or w/e lvl, I put it in the accessory slot, close inventory, open it again, and Wisp is back to lvl 1.
Could you fix this issue please ?
It's not generating any errors in BepInEx logs.
Thx!

### Screenshots

![1](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.BetterWisps/assets/152396780/2410ab1a-2a70-42ba-8ebb-91a4a658cdec)
![2](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.BetterWisps/assets/152396780/a2956ff3-bad5-4ba7-873d-215b747fc6a2)

### Log File

[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.BetterWisps/files/13500241/LogOutput.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
This is a compatibility issue. My understanding is JC changes the Wisp so that it is incompatible. I've seen blax advise players to remove BW and that JC offers settings to get a similar effect.

**Comment by Atylon63** [comment]
What do you mean by "BW" please ?

**Comment by Atylon63** [comment]
I'm gonna give it a look! thx

**Comment by Atylon63** [comment]
Blaxx fixed it for me with yml file, thx!!

**Comment by Digitalroot** [comment]
Great
